/**
 * Asset Pipeline — generates Flutter type-safe asset accessors.
 *
 * Produces lib/gen/assets.gen.dart with static string constants for every
 * asset collected from the IR. This prevents typo-based runtime crashes
 * (pattern adapted from flutter_gen).
 *
 * Usage in generated code:
 *   Image.asset(Assets.images.logo, fit: BoxFit.cover)
 *   SvgPicture.asset(Assets.icons.icArrow)
 *
 * The actual asset binaries are downloaded by project-zipper.ts at ZIP time.
 */

import type { IRAsset } from '@appvelocity/agent-design-to-code-core';
import type { CodeFile } from '../types.js';

// ─── Public API ───────────────────────────────────────────────────────────────

export function buildAssetAccessorFile(assets: IRAsset[], outputDir = 'lib'): CodeFile {
  const images = assets.filter((a) => a.format !== 'svg');
  const icons  = assets.filter((a) => a.format === 'svg');

  const lines: string[] = [
    '// assets.gen.dart — auto-generated by DesignToCodeAgent.',
    '// Do not edit manually.',
    '',
    '// ignore_for_file: lines_longer_than_80_chars, constant_identifier_names',
    '',
    'class Assets {',
    '  Assets._();',
    '',
    '  static const images = _AssetImages();',
    '  static const icons  = _AssetIcons();',
    '}',
    '',
    'class _AssetImages {',
    '  const _AssetImages();',
    '',
  ];

  for (const img of images) {
    const constName = toConstName(img.slug || img.name);
    const path = `assets/images/${img.slug}.${img.format}`;
    lines.push(`  String get ${constName} => '${path}';`);
  }
  if (images.length === 0) {
    lines.push('  // No image assets detected');
  }

  lines.push('}', '', 'class _AssetIcons {', '  const _AssetIcons();', '');

  for (const icon of icons) {
    const constName = toConstName(icon.slug || icon.name);
    const path = `assets/icons/${icon.slug}.svg`;
    lines.push(`  String get ${constName} => '${path}';`);
  }
  if (icons.length === 0) {
    lines.push('  // No SVG icon assets detected');
  }

  lines.push('}', '');

  return {
    path: `${outputDir}/gen/assets.gen.dart`,
    content: lines.join('\n'),
    language: 'dart',
  };
}

/**
 * Returns pubspec.yaml asset entries for all detected assets.
 * Used by project-assembler to declare assets correctly.
 */
export function buildPubspecAssetEntries(assets: IRAsset[]): string[] {
  const hasImages = assets.some((a) => a.format !== 'svg');
  const hasIcons  = assets.some((a) => a.format === 'svg');

  const entries: string[] = [];
  if (hasImages) {
    entries.push('    - assets/images/');
    entries.push('    - assets/images/2.0x/');
    entries.push('    - assets/images/3.0x/');
  }
  if (hasIcons) {
    entries.push('    - assets/icons/');
  }
  return entries;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toConstName(slug: string): string {
  // ic_home_btn → icHomeBtn (lowerCamelCase)
  return slug
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase())
    .replace(/^[0-9]/, 'asset$&');
}
