/**
 * FlutterGenerator
 *
 * Orchestrates style-mapper, token-mapper, and widget-renderer to produce
 * a complete Flutter CodeBundle from a DesignIR.
 */

import type { DesignIR } from '@appvelocity/agent-design-to-code-core';
import { BaseGenerator } from '../base-generator.js';
import type { CodeBundle, CodeFile, AssetFile, GenerationScope, GeneratorOptions, GeneratorResult } from '../types.js';
import { renderScreen, renderComponent } from './widget-renderer.js';
import { buildTokenFiles } from './token-mapper.js';
import { toPascalCase } from '../utils/naming.js';

// Standard Flutter pub.dev dependencies
const FLUTTER_DEPENDENCIES: Record<string, string> = {
  flutter:           'sdk: flutter',
  cupertino_icons:   '^1.0.8',
};

export class FlutterGenerator extends BaseGenerator {
  readonly framework = 'flutter' as const;

  generate(
    ir: DesignIR,
    scope: GenerationScope,
    options: GeneratorOptions = {}
  ): GeneratorResult {
    const outDir = options.outputDir ?? 'lib';
    const { screens, components } = this.filterByScope(ir, scope);
    const warnings: string[] = [];
    const files: CodeFile[] = [];

    // ── Generate in priority order ──────────────────────────────────────────
    const generateScreens = (): void => {
      for (const screen of screens) {
        try {
          files.push(renderScreen(screen, ir.tokens, outDir, warnings));
          if (options.includeTests) {
            files.push(buildStubTestFile(
              toPascalCase(screen.componentName || screen.name),
              'screen',
              outDir
            ));
          }
        } catch (err) {
          warnings.push(`Screen '${screen.name}': ${String(err)}`);
        }
      }
    };

    const generateComponents = (): void => {
      for (const component of components) {
        try {
          files.push(renderComponent(component, ir.tokens, outDir, warnings));
          if (options.includeTests) {
            files.push(buildStubTestFile(
              toPascalCase(component.componentName || component.name),
              'widget',
              outDir
            ));
          }
        } catch (err) {
          warnings.push(`Component '${component.name}': ${String(err)}`);
        }
      }
    };

    if (scope.priority === 'screens-first') {
      generateScreens();
      generateComponents();
    } else {
      generateComponents();
      generateScreens();
    }

    // ── Design tokens ───────────────────────────────────────────────────────
    files.push(...buildTokenFiles(ir.tokens, outDir));

    // ── Assets ──────────────────────────────────────────────────────────────
    const assets: AssetFile[] = ir.assets
      .filter((a) => !!a.url)
      .map((a) => ({
        path: `${outDir}/assets/${a.slug}.${a.format}`,
        url:  a.url as string,
      }));

    // ── Assets folder placeholder ────────────────────────────────────────────
    files.push(buildAssetsPlaceholder(outDir));

    // ── README ───────────────────────────────────────────────────────────────
    files.push(buildReadme(ir.fileName, screens, components, FLUTTER_DEPENDENCIES, outDir));

    const bundle: CodeBundle = {
      framework: 'flutter',
      files,
      assets,
      dependencies: FLUTTER_DEPENDENCIES,
    };

    return {
      bundle,
      warnings,
      stats: {
        screenCount:    screens.length,
        componentCount: components.length,
        assetCount:     assets.length,
        fileCount:      files.length,
      },
    };
  }
}

// ─── Assets placeholder ───────────────────────────────────────────────────────

function buildAssetsPlaceholder(outDir: string): CodeFile {
  return {
    path: `${outDir}/assets/.gitkeep`,
    content: '# Place project assets (images, icons, fonts) here.\n',
    language: 'dart',
  };
}

// ─── README ───────────────────────────────────────────────────────────────────

function buildReadme(
  fileName: string,
  screens: { name: string }[],
  components: { name: string }[],
  deps: Record<string, string>,
  outDir: string
): CodeFile {
  const screenList = screens.map((s) => `- \`${outDir}/screens/${s.name.toLowerCase()}.dart\``).join('\n') || '_None_';
  const componentList = components.map((c) => `- \`${outDir}/widgets/${c.name.toLowerCase()}.dart\``).join('\n') || '_None_';
  const depLines = Object.entries(deps).map(([p, v]) => `  ${p}: ${v}`).join('\n');

  const content = `# Generated Flutter Project

> Auto-generated by **DesignToCodeAgent** from Figma file: **${fileName}**
> Review all files before committing to production.

---

## Project Dependencies

Add the following to your \`pubspec.yaml\`:

\`\`\`yaml
dependencies:
${depLines}
\`\`\`

Then install:

\`\`\`bash
flutter pub get
\`\`\`

---

## Generated Files

### Screens
${screenList}

### Widgets
${componentList}

### Design Tokens
- \`${outDir}/tokens/app_colors.dart\` — color constants
- \`${outDir}/tokens/app_text_styles.dart\` — typography styles

---

## Integrating with Your Main Codebase

1. Copy the \`${outDir}/\` folder into your Flutter project.
2. Import screens in your router:

\`\`\`dart
import 'package:your_app/${outDir}/screens/home_screen.dart';
\`\`\`

3. Import tokens for consistent styling:

\`\`\`dart
import 'package:your_app/${outDir}/tokens/app_colors.dart';
import 'package:your_app/${outDir}/tokens/app_text_styles.dart';
\`\`\`

---

## Asset Linking

Static assets are located in \`${outDir}/assets/\`.

Declare them in \`pubspec.yaml\`:

\`\`\`yaml
flutter:
  assets:
    - ${outDir}/assets/
\`\`\`

Reference assets in code:

\`\`\`dart
Image.asset('${outDir}/assets/hero.png')
\`\`\`

---

## Notes

- All widgets extend \`StatelessWidget\` by default. Convert to \`StatefulWidget\` when state management is needed.
- Design tokens are plain Dart constants — no runtime theming library required.
- Run \`dart format lib/\` and \`dart fix --apply\` after integration for idiomatic formatting.
- Files are auto-generated; manual edits will be overwritten on re-generation.
`;

  return { path: 'README.md', content, language: 'dart' };
}

// ─── Stub test file ───────────────────────────────────────────────────────────

function buildStubTestFile(
  name: string,
  kind: 'screen' | 'widget',
  outDir: string
): CodeFile {
  const dir = kind === 'screen' ? 'screens' : 'widgets';
  const content = [
    `import 'package:flutter/material.dart';`,
    `import 'package:flutter_test/flutter_test.dart';`,
    `import '../${dir}/${name.toLowerCase()}.dart';`,
    ``,
    `void main() {`,
    `  testWidgets('${name} renders without crashing', (tester) async {`,
    `    await tester.pumpWidget(`,
    `      const MaterialApp(home: ${name}()),`,
    `    );`,
    `    expect(find.byType(${name}), findsOneWidget);`,
    `  });`,
    `}`,
    ``,
  ].join('\n');

  return {
    path: `${outDir}/test/${dir}/${name.toLowerCase()}_test.dart`,
    content,
    language: 'dart',
  };
}
