/**
 * Flutter token mapper.
 *
 * Converts IRTokenSet → two Dart token files:
 *   lib/tokens/app_colors.dart
 *   lib/tokens/app_text_styles.dart
 */

import type { IRTokenSet } from '@appvelocity/agent-design-to-code-core';
import type { CodeFile } from '../types.js';
import { toIdentifier } from '../utils/naming.js';
import { hexToFlutterColor } from './style-mapper.js';

export function buildTokenFiles(tokens: IRTokenSet, outputDir = 'lib'): CodeFile[] {
  return [
    buildColorsFile(tokens, outputDir),
    buildTextStylesFile(tokens, outputDir),
  ];
}

// ─── app_colors.dart ──────────────────────────────────────────────────────────

function buildColorsFile(tokens: IRTokenSet, outputDir: string): CodeFile {
  const lines: string[] = [
    `// app_colors.dart — auto-generated by DesignToCodeAgent.`,
    `// Do not edit manually.`,
    `import 'package:flutter/material.dart';`,
    ``,
    `class AppColors {`,
    `  AppColors._();`,
    ``,
  ];

  for (const [key, token] of Object.entries(tokens.colors)) {
    const name = toIdentifier(key);
    lines.push(`  static const Color ${name} = Color(${hexToFlutterColor(token.hex)});`);
  }

  // Add spacing constants too
  if (Object.keys(tokens.spacing).length > 0) {
    lines.push(``, `  // Spacing`);
    for (const [key, value] of Object.entries(tokens.spacing)) {
      lines.push(`  static const double ${toIdentifier(key)} = ${value};`);
    }
  }

  if (Object.keys(tokens.radii).length > 0) {
    lines.push(``, `  // Radii`);
    for (const [key, value] of Object.entries(tokens.radii)) {
      lines.push(`  static const double ${toIdentifier(key)} = ${value};`);
    }
  }

  lines.push(`}`, ``);

  return {
    path: `${outputDir}/tokens/app_colors.dart`,
    content: lines.join('\n'),
    language: 'dart',
  };
}

// ─── app_text_styles.dart ─────────────────────────────────────────────────────

function buildTextStylesFile(tokens: IRTokenSet, outputDir: string): CodeFile {
  const lines: string[] = [
    `// app_text_styles.dart — auto-generated by DesignToCodeAgent.`,
    `// Do not edit manually.`,
    `import 'package:flutter/material.dart';`,
    ``,
    `class AppTextStyles {`,
    `  AppTextStyles._();`,
    ``,
  ];

  for (const [key, token] of Object.entries(tokens.typography)) {
    const name = toIdentifier(key);
    const parts: string[] = [
      `fontFamily: '${token.fontFamily}'`,
      `fontSize: ${token.fontSize}`,
      `fontWeight: FontWeight.w${token.fontWeight}`,
    ];
    if (token.lineHeight !== undefined) parts.push(`height: ${(token.lineHeight / token.fontSize).toFixed(2)}`);
    if (token.letterSpacing !== undefined) parts.push(`letterSpacing: ${token.letterSpacing}`);

    lines.push(
      `  static const TextStyle ${name} = TextStyle(`,
      ...parts.map((p) => `    ${p},`),
      `  );`,
    );
  }

  lines.push(`}`, ``);

  return {
    path: `${outputDir}/tokens/app_text_styles.dart`,
    content: lines.join('\n'),
    language: 'dart',
  };
}
