/**
 * Handlebars template sources for React Native and Flutter code generation.
 *
 * Stored as TypeScript string constants so they work correctly in any module
 * system (CJS / ESM) without requiring runtime file-system access.
 *
 * Template variables:
 *   React Native:
 *     {{componentName}}   — PascalCase component name
 *     {{tag}}             — "Screen" | "Component"
 *     {{{body}}}          — pre-rendered JSX tree (triple-brace = no HTML escaping)
 *     {{#each imports}}   — list of RN component names to import
 *     {{{stylesBlock}}}   — pre-rendered StyleSheet.create({...}) block
 *
 *   Flutter:
 *     {{className}}       — PascalCase class name
 *     {{tag}}             — "Screen" | "Widget"
 *     {{{body}}}          — pre-rendered Dart widget tree
 */

// ─── React Native ─────────────────────────────────────────────────────────────

export const RN_COMPONENT_TEMPLATE = `\
/**
 * {{componentName}} — auto-generated {{tag}}
 * Generated by DesignToCodeAgent. Review before committing.
 */
import React from 'react';
import {
  StyleSheet,
{{#each imports}}
  {{this}},
{{/each}}
} from 'react-native';

export function {{componentName}}(): React.JSX.Element {
  return (
{{{body}}}
  );
}

{{{stylesBlock}}}
`;

// ─── Flutter ──────────────────────────────────────────────────────────────────

// In Dart, a `return` statement may have its expression on the following line.
// The body string is rendered at depth=2 (4-space indent) by FlutterViewModelBuilder,
// so placing `{{{body}}}` on its own line avoids the double-indent that would result
// from `    return {{{body}}}` (which produces `    return     Container(...)`).
export const FLUTTER_COMPONENT_TEMPLATE = `\
// {{className}} — auto-generated {{tag}}
// Generated by DesignToCodeAgent. Review before committing.
import 'package:flutter/material.dart';

class {{className}} extends StatelessWidget {
  const {{className}}({super.key});

  @override
  Widget build(BuildContext context) {
    return
{{{body}}};
  }
}
`;
