/**
 * ReactNativeGenerator
 *
 * Orchestrates style-mapper, token-mapper, and component-renderer to produce
 * a complete React Native CodeBundle from a DesignIR.
 */

import type { DesignIR } from '@appvelocity/agent-design-to-code-core';
import { BaseGenerator } from '../base-generator.js';
import type { CodeBundle, CodeFile, AssetFile, GenerationScope, GeneratorOptions, GeneratorResult } from '../types.js';
import { renderScreen, renderComponent } from './component-renderer.js';
import { buildTokensFile } from './token-mapper.js';
import { toPascalCase } from '../utils/naming.js';

// Standard React Native peer dependencies
const RN_DEPENDENCIES: Record<string, string> = {
  react:             '18.x',
  'react-native':    '0.74.x',
  '@types/react':    '^18.0.0',
};

export class ReactNativeGenerator extends BaseGenerator {
  readonly framework = 'react-native' as const;

  generate(
    ir: DesignIR,
    scope: GenerationScope,
    options: GeneratorOptions = {}
  ): GeneratorResult {
    const outDir = options.outputDir ?? 'src';
    const { screens, components } = this.filterByScope(ir, scope);
    const warnings: string[] = [];
    const files: CodeFile[] = [];

    // ── Generate in priority order ──────────────────────────────────────────
    const generateScreens = (): void => {
      for (const screen of screens) {
        try {
          files.push(renderScreen(screen, ir.tokens, outDir));
          if (options.includeTests) {
            files.push(buildStubTestFile(
              toPascalCase(screen.componentName || screen.name),
              'screen',
              outDir
            ));
          }
        } catch (err) {
          warnings.push(`Screen '${screen.name}': ${String(err)}`);
        }
      }
    };

    const generateComponents = (): void => {
      for (const component of components) {
        try {
          files.push(renderComponent(component, ir.tokens, outDir));
          if (options.includeTests) {
            files.push(buildStubTestFile(
              toPascalCase(component.componentName || component.name),
              'component',
              outDir
            ));
          }
        } catch (err) {
          warnings.push(`Component '${component.name}': ${String(err)}`);
        }
      }
    };

    if (scope.priority === 'screens-first') {
      generateScreens();
      generateComponents();
    } else {
      generateComponents();
      generateScreens();
    }

    // ── Design tokens ───────────────────────────────────────────────────────
    files.push(buildTokensFile(ir.tokens, outDir));

    // ── Assets ──────────────────────────────────────────────────────────────
    const assets: AssetFile[] = ir.assets
      .filter((a) => !!a.url)
      .map((a) => ({
        path: `${outDir}/assets/${a.slug}.${a.format}`,
        url:  a.url as string,
      }));

    // ── Assets folder placeholder ────────────────────────────────────────────
    // Ensures the assets/ directory is always present in the bundle even when
    // no Figma assets were resolved to URLs.
    files.push(buildAssetsPlaceholder(outDir));

    // ── README ───────────────────────────────────────────────────────────────
    files.push(buildReadme('react-native', ir.fileName, screens, components, RN_DEPENDENCIES, outDir));

    const bundle: CodeBundle = {
      framework: 'react-native',
      files,
      assets,
      dependencies: RN_DEPENDENCIES,
    };

    return {
      bundle,
      warnings,
      stats: {
        screenCount:    screens.length,
        componentCount: components.length,
        assetCount:     assets.length,
        fileCount:      files.length,
      },
    };
  }
}

// ─── Assets placeholder ───────────────────────────────────────────────────────

function buildAssetsPlaceholder(outDir: string): CodeFile {
  return {
    path: `${outDir}/assets/.gitkeep`,
    content: '# Place project assets (images, icons, fonts) here.\n',
    language: 'typescript',
  };
}

// ─── README ───────────────────────────────────────────────────────────────────

function buildReadme(
  _framework: string,
  fileName: string,
  screens: { name: string }[],
  components: { name: string }[],
  deps: Record<string, string>,
  outDir: string
): CodeFile {
  const screenList = screens.map((s) => `- \`${outDir}/screens/${s.name}.tsx\``).join('\n') || '_None_';
  const componentList = components.map((c) => `- \`${outDir}/components/${c.name}.tsx\``).join('\n') || '_None_';
  const depLines = Object.entries(deps).map(([p, v]) => `  "${p}": "${v}"`).join(',\n');

  const content = `# Generated React Native Project

> Auto-generated by **DesignToCodeAgent** from Figma file: **${fileName}**
> Review all files before committing to production.

---

## Project Dependencies

Add the following to your \`package.json\`:

\`\`\`json
{
  "dependencies": {
${depLines}
  }
}
\`\`\`

Then install:

\`\`\`bash
npm install
# or
yarn install
\`\`\`

---

## Generated Files

### Screens
${screenList}

### Components
${componentList}

### Design Tokens
- \`${outDir}/tokens/tokens.ts\` — colors, typography, spacing, radii

---

## Integrating with Your Main Codebase

1. Copy the \`${outDir}/\` folder into your React Native project root.
2. Import screens in your navigator:

\`\`\`tsx
import { HomeScreen } from './${outDir}/screens/HomeScreen';
\`\`\`

3. Import tokens for consistent styling:

\`\`\`tsx
import { colors, typography } from './${outDir}/tokens/tokens';
\`\`\`

---

## Asset Linking

Static assets (images, icons) are located in \`${outDir}/assets/\`.

For React Native, add asset references in \`metro.config.js\`:

\`\`\`js
module.exports = {
  resolver: {
    assetExts: ['png', 'jpg', 'svg', 'gif'],
  },
};
\`\`\`

Reference assets in code:

\`\`\`tsx
<Image source={require('./${outDir}/assets/hero.png')} />
\`\`\`

---

## Notes

- All styles use \`StyleSheet.create()\` for optimal React Native performance.
- Design tokens are exported as plain objects — no runtime theming library required.
- Files are auto-generated; manual edits will be overwritten on re-generation.
`;

  return { path: 'README.md', content, language: 'typescript' };
}

// ─── Stub test file ───────────────────────────────────────────────────────────

function buildStubTestFile(
  name: string,
  kind: 'screen' | 'component',
  outDir: string
): CodeFile {
  const dir = kind === 'screen' ? 'screens' : 'components';
  const importPath = `./${name}`;
  const content = [
    `import React from 'react';`,
    `import { render } from '@testing-library/react-native';`,
    `import { ${name} } from '${importPath}';`,
    ``,
    `describe('${name}', () => {`,
    `  it('renders without crashing', () => {`,
    `    const { toJSON } = render(<${name} />);`,
    `    expect(toJSON()).toBeTruthy();`,
    `  });`,
    `});`,
    ``,
  ].join('\n');

  return {
    path: `${outDir}/${dir}/${name}.test.tsx`,
    content,
    language: 'typescript',
  };
}
