/**
 * React Native token mapper.
 *
 * Converts IRTokenSet → src/tokens/tokens.ts
 */

import type { IRTokenSet } from '@appvelocity/agent-design-to-code-core';
import type { CodeFile } from '../types.js';
import { toIdentifier } from '../utils/naming.js';

export function buildTokensFile(tokens: IRTokenSet, outputDir = 'src'): CodeFile {
  const lines: string[] = [
    '/**',
    ' * Design tokens — auto-generated by DesignToCodeAgent.',
    ' * Do not edit manually.',
    ' */',
    '',
  ];

  // ── Colors ────────────────────────────────────────────────────────────────
  lines.push('export const COLORS = {');
  for (const [key, token] of Object.entries(tokens.colors)) {
    lines.push(`  ${toIdentifier(key)}: '${token.hex}',`);
  }
  lines.push('} as const;', '');

  // ── Typography ────────────────────────────────────────────────────────────
  lines.push('export const TYPOGRAPHY = {');
  for (const [key, token] of Object.entries(tokens.typography)) {
    lines.push(
      `  ${toIdentifier(key)}: {`,
      `    fontFamily: '${token.fontFamily}',`,
      `    fontSize: ${token.fontSize},`,
      `    fontWeight: '${token.fontWeight}' as const,`,
      token.lineHeight !== undefined ? `    lineHeight: ${token.lineHeight},` : '',
      token.letterSpacing !== undefined ? `    letterSpacing: ${token.letterSpacing},` : '',
      '  },'
    );
  }
  lines.push('} as const;', '');

  // ── Spacing ───────────────────────────────────────────────────────────────
  lines.push('export const SPACING = {');
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`  ${toIdentifier(key)}: ${value},`);
  }
  lines.push('} as const;', '');

  // ── Radii ─────────────────────────────────────────────────────────────────
  lines.push('export const RADII = {');
  for (const [key, value] of Object.entries(tokens.radii)) {
    lines.push(`  ${toIdentifier(key)}: ${value},`);
  }
  lines.push('} as const;');

  const content = lines.filter((l) => l !== undefined).join('\n') + '\n';

  return {
    path: `${outputDir}/tokens/tokens.ts`,
    content,
    language: 'typescript',
  };
}
