/**
 * Node 7 — CodeGeneratorAgent  (LLM-based, replaces template engine)
 *
 * Architecture change: instead of Handlebars templates + ViewModel builders,
 * each screen/component is generated by a dedicated LLM call with a rich,
 * structured prompt derived directly from the DesignIR.
 *
 * ┌────────────────────────────────────────────────────────────────────┐
 * │  GENERATION LOOP (per screen / component)                          │
 * │                                                                    │
 * │  1. Serialize IR → compact human-readable prompt tree              │
 * │  2. LLM call with full project context                             │
 * │  3. Gate 1 (pre-write): Babel AST parse + structural check        │
 * │     → if fail → Gate 5 repair loop (max 3 attempts)               │
 * │  4. Accept file (with escalation comment if repair exhausted)      │
 * │  5. Write to temp workspace                                        │
 * │  6. Every GATE3_INTERVAL files → Gate 3: workspace tsc --noEmit   │
 * │     → per-file repair for any new errors                          │
 * └────────────────────────────────────────────────────────────────────┘
 *
 * Deterministic files (tokens, navigation types) are generated without LLM
 * so they are always correct and cheap.
 *
 * Output: `generatedCode` (CodeBundle) — compatible with projectAssembler.
 */

import type {
  IRScreen,
  IRComponent,
  IRTokenSet,
} from '@appvelocity/agent-design-to-code-core';
import type { CodeFile, AssetFile }  from '@appvelocity/agent-design-to-code-generators';
import { createLLMClient }           from '../utils/llm-client.js';
import { makeLogEntry }              from '../utils/logger.js';
import { serializeScreen, serializeComponent, serializeTokenSummary } from '../utils/ir-serializer.js';
import { generateRNStyleSheet, generateFlutterLayoutConstants } from '../utils/style-generator.js';
import { runGate1, stripMarkdownFences }  from '../utils/gate1-validator.js';
import { WorkspaceSession, groupErrorsByFile } from '../utils/workspace-validator.js';
import { repairFile }                from '../utils/repair-loop.js';
import type { WorkflowState }        from '../types.js';

// ─── Constants ────────────────────────────────────────────────────────────────

/** Run workspace tsc check after every N generated files. */
const GATE3_INTERVAL = 5;

// ─── System prompts ───────────────────────────────────────────────────────────

const RN_SYSTEM_PROMPT = `You are a React Native TypeScript expert generating production-quality, compilable code.

ABSOLUTE RULES — never violate:
1. Return ONLY raw TypeScript/TSX file content. No markdown fences, no explanations.
2. Import ONLY from packages listed in "Available packages" or exact relative paths in "Project files".
3. Use StyleSheet.create for ALL styles — no inline style objects ever.
4. Export pattern: named export AND default export at bottom of file.
   Example:  export function HomeScreen(): React.JSX.Element { ... }
             export default HomeScreen;
5. Strict TypeScript: type every variable, no implicit any, use optional chaining (?.) for nullable values.
6. Escape literal braces in JSX text: use {'{'} and {'}'} for { }, never raw curly braces.
7. Never reference a component that is not imported in this very file.
8. For images: use { uri: 'placeholder_url' } or require('./path') — never undefined src.
9. Wrap every screen in <SafeAreaView style={styles.safeArea}> as the outermost root.
10. Use const instead of function declarations for inline callbacks.`;

const FLUTTER_SYSTEM_PROMPT = `You are a Flutter/Dart expert generating production-quality, compilable Dart code.

ABSOLUTE RULES — never violate:
1. Return ONLY raw Dart source code. No markdown fences, no explanations.
2. Always import 'package:flutter/material.dart'.
3. Extend StatelessWidget or StatefulWidget — never use raw Widget subclasses.
4. Use const constructors wherever the value is compile-time constant.
5. Handle null safety: use ? for nullable types, ?? for defaults, ?. for optional chaining.
6. Never use dynamic type — annotate all variables explicitly.
7. Use AppColors / AppTextStyles from lib/tokens/ for all design values.
8. Image.network() for remote images; Image.asset() for local — never bare Image().
9. Wrap every screen body in SafeArea(child: ...).
10. Declare the class in a single file; no partial classes.`;

// ─── Node ─────────────────────────────────────────────────────────────────────

export async function codeGeneratorAgent(
  state: WorkflowState
): Promise<Partial<WorkflowState>> {
  if (!state.designIR) {
    throw new Error('DesignIR not available. IRBuilderAgent must run first.');
  }
  if (!state.executionPlan) {
    throw new Error('ExecutionPlan not available. GenerationPlannerAgent must run first.');
  }

  const ir        = state.designIR;
  const plan      = state.executionPlan;
  const framework = state.targetFramework;
  const llm       = createLLMClient();
  const model     = process.env['OPENAI_MODEL'] ?? 'gpt-4o';
  const logs: ReturnType<typeof makeLogEntry>[] = [];
  const warnings: string[] = [];

  // ── Step 1: Deterministic files ──────────────────────────────────────────────
  const files: CodeFile[] = [];

  if (framework === 'react-native') {
    files.push(buildRNTokensFile(ir.tokens));
    files.push(buildRNNavTypesFile(plan.screens));
  } else {
    files.push(...buildFlutterTokenFiles(ir.tokens));
  }

  // ── Step 2: Build project context (updated incrementally) ──────────────────
  const tokenSummary     = serializeTokenSummary(ir.tokens);
  const generatedFilePaths: string[] = files.map((f) => f.path);

  // ── Step 3: Create temp workspace ──────────────────────────────────────────
  const workspace = await WorkspaceSession.create(framework);
  let gate3Due    = GATE3_INTERVAL; // generate this many files, then run Gate 3

  try {
    // Seed workspace with deterministic files
    for (const f of files) {
      await workspace.writeFile(f.path, f.content);
    }

    // ── Step 4: Generate screens ───────────────────────────────────────────────
    const screensToGen = getScreens(ir, plan.screens);
    logs.push(makeLogEntry('info', `[CodeGen] Generating ${screensToGen.length} screen(s) via LLM…`));

    const screenFiles = await generateBatch(
      screensToGen.map((s) => ({
        kind:       'screen' as const,
        id:         s.id,
        name:       s.componentName,
        serialized: serializeScreen(s),
        filePath:   framework === 'react-native'
          ? `src/screens/${s.componentName}.tsx`
          : `lib/screens/${toSnake(s.componentName)}_screen.dart`,
        styleSheet: framework === 'react-native'
          ? generateRNStyleSheet(s).code
          : generateFlutterLayoutConstants(s),
      })),
      {
        llm, model, framework, tokenSummary, generatedFilePaths,
        stateManagement: state.stateManagement,
        workspace, gate3Due, warnings, logs, assets: ir.assets,
      }
    );
    files.push(...screenFiles);
    generatedFilePaths.push(...screenFiles.map((f) => f.path));
    gate3Due -= screensToGen.length;

    // ── Step 5: Generate components ────────────────────────────────────────────
    const componentsToGen = getComponents(ir, plan.components);
    if (componentsToGen.length > 0) {
      logs.push(makeLogEntry('info', `[CodeGen] Generating ${componentsToGen.length} component(s) via LLM…`));

      const componentFiles = await generateBatch(
        componentsToGen.map((c) => ({
          kind:       'component' as const,
          id:         c.id,
          name:       c.componentName,
          serialized: serializeComponent(c),
          filePath:   framework === 'react-native'
            ? `src/components/${c.componentName}.tsx`
            : `lib/widgets/${toSnake(c.componentName)}_widget.dart`,
          styleSheet: framework === 'react-native'
            ? generateRNStyleSheet(c).code
            : generateFlutterLayoutConstants(c),
        })),
        {
          llm, model, framework, tokenSummary, generatedFilePaths,
          stateManagement: state.stateManagement,
          workspace, gate3Due, warnings, logs, assets: ir.assets,
        }
      );
      files.push(...componentFiles);
    }

    // ── Step 6: Final Gate 3 pass ──────────────────────────────────────────────
    if (framework === 'react-native') {
      logs.push(makeLogEntry('info', '[CodeGen] Gate 3: final workspace tsc check…'));
      const errors = await workspace.runCheck();
      if (errors.length > 0) {
        const repaired = await repairWorkspaceErrors(
          errors, files, llm, model, framework, workspace, logs
        );
        // Merge repaired content back into files array
        for (const [path, content] of repaired) {
          const idx = files.findIndex((f) => f.path === path);
          if (idx >= 0) files[idx] = { ...files[idx]!, content };
        }
        const remaining = (await workspace.runCheck()).length;
        logs.push(makeLogEntry(
          remaining === 0 ? 'success' : 'warning',
          `[CodeGen] Gate 3 final: ${errors.length - remaining} error(s) fixed, ${remaining} remaining`
        ));
      } else {
        logs.push(makeLogEntry('success', '[CodeGen] Gate 3 final: workspace clean'));
      }
    }
  } finally {
    await workspace.cleanup();
  }

  // ── Step 7: Collect assets ──────────────────────────────────────────────────
  const assets: AssetFile[] = ir.assets
    .filter((a): a is typeof a & { url: string } => !!a.url)
    .map((a) => ({
      path: `assets/${a.format === 'svg' ? 'icons' : 'images'}/${a.slug}.${a.format}`,
      url:  a.url,
    }));

  const scaledCount = warnings.filter((w) => w.includes('repair')).length;
  logs.push(makeLogEntry('success',
    `[CodeGen] ${files.length} files generated` +
    (scaledCount > 0 ? ` (${scaledCount} repair(s) applied)` : '') +
    `, ${assets.length} asset(s) collected`
  ));

  warnings.forEach((w) => logs.push(makeLogEntry('warning', w)));

  return {
    generatedCode: {
      framework,
      files,
      assets,
      dependencies: getCoreDependencies(framework, state.stateManagement),
    },
    currentStep: 'CodeGeneratorAgent',
    logs,
  };
}

// ─── Batch generation ─────────────────────────────────────────────────────────

interface GenerationTarget {
  kind:         'screen' | 'component';
  id:           string;
  name:         string;
  serialized:   string;
  filePath:     string;
  /** Pre-generated StyleSheet.create() or Flutter layout constants — LLM references these, does not invent them */
  styleSheet?:  string;
}

interface BatchContext {
  llm:              ReturnType<typeof createLLMClient>;
  model:            string;
  framework:        'react-native' | 'flutter';
  tokenSummary:     string;
  generatedFilePaths: string[];
  stateManagement:  string;
  workspace:        WorkspaceSession;
  gate3Due:         number;
  warnings:         string[];
  logs:             ReturnType<typeof makeLogEntry>[];
  assets:           import('@appvelocity/agent-design-to-code-core').IRAsset[];
}

async function generateBatch(
  targets: GenerationTarget[],
  ctx:     BatchContext
): Promise<CodeFile[]> {
  // Generate all files in parallel for speed
  const results = await Promise.allSettled(
    targets.map((target) => generateSingleFile(target, ctx))
  );

  const files: CodeFile[] = [];
  for (const [i, result] of results.entries()) {
    const target = targets[i]!;
    if (result.status === 'fulfilled') {
      files.push(result.value);
      ctx.generatedFilePaths.push(result.value.path);
      await ctx.workspace.writeFile(result.value.path, result.value.content);
    } else {
      ctx.warnings.push(`[CodeGen] Failed to generate ${target.filePath}: ${result.reason}`);
      // Emit a minimal stub so the rest of the project can still compile
      const stub = buildStubFile(target.filePath, target.name, ctx.framework);
      files.push(stub);
      await ctx.workspace.writeFile(stub.path, stub.content);
    }
  }

  // Gate 3: run workspace tsc after every GATE3_INTERVAL files
  if (ctx.framework === 'react-native' && ctx.workspace.fileCount >= ctx.gate3Due) {
    ctx.gate3Due += GATE3_INTERVAL;
    const errors = await ctx.workspace.runCheck();
    if (errors.length > 0) {
      ctx.logs.push(makeLogEntry('info',
        `[CodeGen] Gate 3: ${errors.length} error(s) — repairing…`
      ));
      const repaired = await repairWorkspaceErrors(
        errors, files, ctx.llm, ctx.model, ctx.framework, ctx.workspace, ctx.logs
      );
      for (const [path, content] of repaired) {
        const idx = files.findIndex((f) => f.path === path);
        if (idx >= 0) files[idx] = { ...files[idx]!, content };
      }
    }
  }

  return files;
}

// ─── Single file generation ───────────────────────────────────────────────────

async function generateSingleFile(
  target: GenerationTarget,
  ctx:    BatchContext
): Promise<CodeFile> {
  const prompt = buildPrompt(target, ctx);
  const system = ctx.framework === 'react-native' ? RN_SYSTEM_PROMPT : FLUTTER_SYSTEM_PROMPT;

  let content = '';
  let attempt = 0;
  const maxGenAttempts = 2;

  while (attempt < maxGenAttempts) {
    attempt++;
    try {
      const response = await ctx.llm.chat({
        model:      ctx.model,
        system,
        messages:   [{ role: 'user', content: prompt }],
        max_tokens: 4096,
      });
      content = stripMarkdownFences(response.content);
    } catch (err) {
      if (attempt >= maxGenAttempts) throw err;
      continue;
    }

    // ── Gate 1: pre-write validation ──────────────────────────────────────────
    const gate1 = runGate1(content, ctx.framework);

    if (gate1.valid && !gate1.structureIssue) break; // accepted

    // Gate 1 failed — enter Gate 5 repair loop
    const repairErrors = gate1.errors.length > 0
      ? gate1.errors
      : [{ line: 0, col: 0, message: gate1.structureIssue ?? 'Structure check failed' }];

    const repairResult = await repairFile(
      ctx.llm, ctx.model, target.filePath, content, repairErrors, ctx.framework
    );
    content = repairResult.content;

    if (repairResult.repaired) break;
    // If repair exhausted, fall through with the escalated content
    break;
  }

  const lang: CodeFile['language'] = ctx.framework === 'react-native' ? 'typescript' : 'dart';
  return { path: target.filePath, content, language: lang };
}

// ─── Workspace error repair ───────────────────────────────────────────────────

async function repairWorkspaceErrors(
  errors:    import('../types.js').CompileError[],
  files:     CodeFile[],
  llm:       ReturnType<typeof createLLMClient>,
  model:     string,
  framework: 'react-native' | 'flutter',
  workspace: WorkspaceSession,
  logs:      ReturnType<typeof makeLogEntry>[]
): Promise<Map<string, string>> {
  const byFile  = groupErrorsByFile(errors);
  const repaired = new Map<string, string>();

  await Promise.allSettled(
    [...byFile.entries()]
      .sort((a, b) => b[1].length - a[1].length) // most broken first
      .slice(0, 10)
      .map(async ([filePath, fileErrors]) => {
        const file = files.find((f) => f.path === filePath);
        if (!file) return;

        const result = await repairFile(
          llm, model, filePath, file.content, fileErrors, framework
        );

        repaired.set(filePath, result.content);
        if (!result.escalated) {
          await workspace.writeFile(filePath, result.content);
        }

        logs.push(makeLogEntry(
          result.repaired ? 'info' : 'warning',
          `[CodeGen] Gate 3 repair ${result.repaired ? 'succeeded' : 'escalated'}: ${filePath} (${fileErrors.length} errors)`
        ));
      })
  );

  return repaired;
}

// ─── Prompt builders ──────────────────────────────────────────────────────────

function buildPrompt(target: GenerationTarget, ctx: BatchContext): string {
  if (ctx.framework === 'react-native') {
    return buildRNPrompt(target, ctx);
  }
  return buildFlutterPrompt(target, ctx);
}

function buildRNPrompt(target: GenerationTarget, ctx: BatchContext): string {
  const navScreens = ctx.generatedFilePaths
    .filter((p) => p.startsWith('src/screens/') && p.endsWith('.tsx'))
    .map((p) => p.replace('src/screens/', '').replace('.tsx', ''))
    .join(', ');

  const existingFiles = ctx.generatedFilePaths
    .map((p) => `  - ${p}`)
    .join('\n');

  // Build asset manifest using bundled require() paths — these match what is written into the ZIP.
  // Never filter missing assets out: the LLM must still generate an <Image> for each one.
  const assetLines = ctx.assets
    .map((a) => {
      const folder = a.format === 'svg' ? 'icons' : 'images';
      const requirePath = `../../assets/${folder}/${a.slug}.${a.format}`;
      return `  - ${a.slug}.${a.format}  →  require('${requirePath}')`;
    })
    .join('\n');

  const styleSection = target.styleSheet
    ? `\n## Pre-generated StyleSheet (ALREADY DEFINED — reference these keys exactly, do NOT redefine)\n\`\`\`typescript\n${target.styleSheet}\n\`\`\`\n`
    : '';

  return `Generate a React Native TypeScript ${target.kind} component.

## Target file
Path: ${target.filePath}
Component name: ${target.name}

## Available packages (import ONLY from these)
- react — React, useState, useEffect, useCallback, useMemo, useRef
- react-native — View, Text, Image, ImageBackground, ScrollView, FlatList, TextInput, TouchableOpacity, Pressable, StyleSheet, Dimensions, Platform, SafeAreaView, StatusBar, ActivityIndicator, KeyboardAvoidingView
- @react-navigation/native — useNavigation
- @react-navigation/native-stack — NativeStackNavigationProp

## Project files already generated (use these relative paths for imports)
${existingFiles || '  (none yet)'}

## Navigation
Screen names: ${navScreens || '(none yet)'}
Import pattern:
  import { useNavigation } from '@react-navigation/native';
  import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
  import type { RootStackParamList } from '../navigation/types';
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  navigation.navigate('ScreenName');

## Design tokens (from src/tokens/tokens.ts)
${ctx.tokenSummary || '(no tokens — use hardcoded values)'}

## State management: ${ctx.stateManagement || 'none'}
${assetLines ? `\n## Image assets — bundled in project ZIP (use the require() paths below exactly)\n${assetLines}\n` : ''}${styleSection}
## Design specification
${target.serialized}

## Critical requirements
- Wrap outermost element in <SafeAreaView style={styles.safeArea}>
- All touchable areas use Pressable or TouchableOpacity with onPress={() => {}} placeholder
- EVERY asset listed above MUST appear as <Image source={require('../../assets/images/slug.png')} /> using the exact require() path shown above — do NOT omit any
- For images NOT in the asset list, use <Image source={{ uri: 'https://via.placeholder.com/400x300' }} />
- All text strings: escape {{ and }} as {'{'} and {'}'}
${target.styleSheet
  ? `- IMPORTANT: The \`styles\` object above is already complete — copy it verbatim at the bottom of the file. Reference \`styles.keyName\` for every element. DO NOT add, remove, or change any style values.`
  : `- StyleSheet.create block at bottom of file with every style referenced in JSX\n- No inline style objects anywhere`}
- Export: export function ${target.name}(): React.JSX.Element {{ ... }}
          export default ${target.name};`;
}

function buildFlutterPrompt(target: GenerationTarget, ctx: BatchContext): string {
  const existingFiles = ctx.generatedFilePaths
    .map((p) => `  - ${p}`)
    .join('\n');

  const assetLines = ctx.assets
    .map((a) => {
      const folder = a.format === 'svg' ? 'icons' : 'images';
      return `  - assets/${folder}/${a.slug}.${a.format}  (${a.name ?? a.slug})`;
    })
    .join('\n');

  const layoutSection = target.styleSheet
    ? `\n## Pre-generated layout constants (ALREADY DEFINED — reference these in your widget tree)\n\`\`\`dart\n${target.styleSheet}\n\`\`\`\n`
    : '';

  return `Generate a Flutter/Dart ${target.kind} widget.

## Target file
Path: ${target.filePath}
Class name: ${target.name}

## Available packages
- package:flutter/material.dart — all Flutter widgets
- package:flutter/cupertino.dart — iOS-style widgets (optional)

## Project files already generated (use these relative paths)
${existingFiles || '  (none yet)'}

## Design tokens
Import from: package:your_app/tokens/app_colors.dart
             package:your_app/tokens/app_text_styles.dart
${ctx.tokenSummary || '(no tokens — use hardcoded values from the design spec)'}

## State management: ${ctx.stateManagement || 'none'}
${assetLines ? `\n## Image assets — bundled in project ZIP (use Image.asset with paths below)\n${assetLines}\n` : ''}${layoutSection}
## Design specification
${target.serialized}

## Critical requirements
- class ${target.name} extends StatelessWidget (use StatefulWidget only if local state needed)
- const constructor: const ${target.name}({super.key});
- SafeArea(child: ...) at the root of the Scaffold body
- EVERY asset listed above MUST appear as Image.asset('assets/images/slug.png', fit: BoxFit.cover) — do NOT omit any
- Every other image: Image.network('https://via.placeholder.com/400x300', errorBuilder: (c,e,s) => const Icon(Icons.broken_image))
- All colours from AppColors, all text styles from AppTextStyles
${target.styleSheet
  ? `- IMPORTANT: The layout constants above are already computed — copy them verbatim at the top of the file and use them for all SizedBox/Container/EdgeInsets dimensions.`
  : `- No hard-coded magic numbers — use const spacing values`}`;
}

// ─── Deterministic file builders ──────────────────────────────────────────────

function buildRNTokensFile(tokens: IRTokenSet): CodeFile {
  const lines: string[] = [
    '// Design tokens — auto-generated by DesignToCodeAgent.',
    '',
  ];

  lines.push('export const COLORS = {');
  for (const [k, v] of Object.entries(tokens.colors).slice(0, 50)) {
    lines.push(`  ${safeId(k)}: '${v.hex}',`);
  }
  lines.push('} as const;', '');

  lines.push('export const TYPOGRAPHY = {');
  for (const [k, v] of Object.entries(tokens.typography).slice(0, 30)) {
    const fw = String(v.fontWeight);
    const ll = [
      `    fontFamily: '${v.fontFamily}',`,
      `    fontSize: ${v.fontSize},`,
      `    fontWeight: '${fw}' as const,`,
      v.lineHeight   !== undefined ? `    lineHeight: ${v.lineHeight},`     : null,
      v.letterSpacing !== undefined ? `    letterSpacing: ${v.letterSpacing},` : null,
    ].filter(Boolean);
    lines.push(`  ${safeId(k)}: {`, ...ll as string[], '  },');
  }
  lines.push('} as const;', '');

  lines.push('export const SPACING = {');
  for (const [k, v] of Object.entries(tokens.spacing).slice(0, 20)) {
    lines.push(`  ${safeId(k)}: ${v},`);
  }
  lines.push('} as const;', '');

  lines.push('export const RADII = {');
  for (const [k, v] of Object.entries(tokens.radii).slice(0, 20)) {
    lines.push(`  ${safeId(k)}: ${v},`);
  }
  lines.push('} as const;');

  return {
    path:     'src/tokens/tokens.ts',
    content:  lines.join('\n') + '\n',
    language: 'typescript',
  };
}

function buildRNNavTypesFile(screenNames: string[]): CodeFile {
  // Deduplicate and convert node IDs to valid TypeScript identifiers.
  // The LLM planner may return Figma node IDs ("13-8804") instead of names;
  // those are mapped to component-safe names here.
  const seen = new Set<string>();
  const params = screenNames
    .map((s) => toComponentName(s))
    .filter((name) => {
      if (seen.has(name)) return false;
      seen.add(name);
      return true;
    })
    .map((name) => `  ${name}: undefined;`)
    .join('\n');

  const content =
    `// Navigation types — auto-generated by DesignToCodeAgent.\n` +
    `export type RootStackParamList = {\n${params}\n};\n`;
  return { path: 'src/navigation/types.ts', content, language: 'typescript' };
}

/** "My Screen Name" → "MyScreenName", "13-8804" → "Screen138804" */
function toComponentName(name: string): string {
  const result = name
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
  return /^\d/.test(result) ? `Screen${result}` : (result || 'Screen');
}

function buildFlutterTokenFiles(tokens: IRTokenSet): CodeFile[] {
  const colorLines = [
    "import 'package:flutter/material.dart';",
    '',
    'class AppColors {',
    '  AppColors._();',
  ];
  for (const [k, v] of Object.entries(tokens.colors).slice(0, 50)) {
    const hex = v.hex.replace('#', '');
    colorLines.push(`  static const Color ${safeId(k)} = Color(0xFF${hex.toUpperCase()});`);
  }
  for (const [k, v] of Object.entries(tokens.spacing).slice(0, 20)) {
    colorLines.push(`  static const double spacing${cap(k)} = ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.radii).slice(0, 20)) {
    colorLines.push(`  static const double radius${cap(k)} = ${v};`);
  }
  colorLines.push('}');

  const styleLines = [
    "import 'package:flutter/material.dart';",
    "import 'app_colors.dart';",
    '',
    'class AppTextStyles {',
    '  AppTextStyles._();',
  ];
  for (const [k, v] of Object.entries(tokens.typography).slice(0, 30)) {
    const fw = typeof v.fontWeight === 'number'
      ? `FontWeight.w${v.fontWeight}`
      : `FontWeight.w${v.fontWeight}`;
    styleLines.push(
      `  static const TextStyle ${safeId(k)} = TextStyle(`,
      `    fontFamily: '${v.fontFamily}',`,
      `    fontSize: ${v.fontSize},`,
      `    fontWeight: ${fw},`,
      '  );',
    );
    if (v.lineHeight !== undefined) {
      styleLines.splice(styleLines.length - 1, 0, `    height: ${(v.lineHeight / v.fontSize).toFixed(2)},`);
    }
  }
  styleLines.push('}');

  return [
    {
      path:     'lib/tokens/app_colors.dart',
      content:  colorLines.filter(Boolean).join('\n') + '\n',
      language: 'dart',
    },
    {
      path:     'lib/tokens/app_text_styles.dart',
      content:  styleLines.filter(Boolean as unknown as (v: string | null) => v is string).join('\n') + '\n',
      language: 'dart',
    },
  ];
}

// ─── Stub file (fallback when LLM call fails) ─────────────────────────────────

function buildStubFile(filePath: string, name: string, framework: 'react-native' | 'flutter'): CodeFile {
  if (framework === 'react-native') {
    return {
      path: filePath,
      language: 'typescript',
      content:
        `// ⚠️  Auto-generation failed for ${name}. This is a placeholder stub.\n` +
        `import React from 'react';\n` +
        `import { View, Text, StyleSheet, SafeAreaView } from 'react-native';\n\n` +
        `export function ${name}(): React.JSX.Element {\n` +
        `  return (\n` +
        `    <SafeAreaView style={styles.safeArea}>\n` +
        `      <View style={styles.container}>\n` +
        `        <Text style={styles.text}>${name}</Text>\n` +
        `      </View>\n` +
        `    </SafeAreaView>\n` +
        `  );\n` +
        `}\n\n` +
        `const styles = StyleSheet.create({\n` +
        `  safeArea:  { flex: 1, backgroundColor: '#fff' },\n` +
        `  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },\n` +
        `  text:      { fontSize: 16, color: '#333' },\n` +
        `});\n\n` +
        `export default ${name};\n`,
    };
  }
  return {
    path: filePath,
    language: 'dart',
    content:
      `// ⚠️  Auto-generation failed for ${name}. This is a placeholder stub.\n` +
      `import 'package:flutter/material.dart';\n\n` +
      `class ${name} extends StatelessWidget {\n` +
      `  const ${name}({super.key});\n\n` +
      `  @override\n` +
      `  Widget build(BuildContext context) {\n` +
      `    return Scaffold(\n` +
      `      body: Center(child: Text('${name}')),\n` +
      `    );\n` +
      `  }\n` +
      `}\n`,
  };
}

// ─── IR selection helpers ─────────────────────────────────────────────────────

function getScreens(
  ir:   import('@appvelocity/agent-design-to-code-core').DesignIR,
  names: string[]
): IRScreen[] {
  if (names.length === 0) return ir.screens;
  const nameSet = new Set(names);
  const byName  = ir.screens.filter((s) => nameSet.has(s.componentName) || nameSet.has(s.name));
  return byName.length > 0 ? byName : ir.screens;
}

function getComponents(
  ir:    import('@appvelocity/agent-design-to-code-core').DesignIR,
  names: string[]
): IRComponent[] {
  if (names.length === 0) return ir.components.slice(0, 15); // cap at 15
  const nameSet = new Set(names);
  return ir.components.filter((c) => nameSet.has(c.componentName) || nameSet.has(c.name));
}

// ─── Core dependency sets ─────────────────────────────────────────────────────

function getCoreDependencies(
  framework:       'react-native' | 'flutter',
  stateManagement: string
): Record<string, string> {
  if (framework === 'flutter') {
    const deps: Record<string, string> = {
      flutter: 'sdk: flutter',
      cupertino_icons: '^1.0.8',
    };
    if (stateManagement === 'riverpod')  deps['flutter_riverpod']  = '^2.5.1';
    if (stateManagement === 'bloc')      deps['flutter_bloc']       = '^8.1.5';
    if (stateManagement === 'provider')  deps['provider']           = '^6.1.2';
    return deps;
  }
  const deps: Record<string, string> = {
    react:         '18.2.0',
    'react-native': '0.74.0',
    '@react-navigation/native':       '^6.1.17',
    '@react-navigation/native-stack': '^6.9.26',
    'react-native-safe-area-context': '^4.10.1',
    'react-native-screens':           '^3.31.1',
  };
  if (stateManagement === 'zustand')  deps['zustand']             = '^4.5.2';
  if (stateManagement === 'redux')    { deps['@reduxjs/toolkit']  = '^2.2.5'; deps['react-redux'] = '^9.1.2'; }
  if (stateManagement === 'jotai')    deps['jotai']               = '^2.8.0';
  return deps;
}

// ─── Small utilities ──────────────────────────────────────────────────────────

function safeId(s: string): string {
  const r = s.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1');
  return r || '_token';
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function toSnake(pascal: string): string {
  return pascal.replace(/([A-Z])/g, (_m, l: string, o: number) => (o > 0 ? '_' : '') + l.toLowerCase());
}
